### ISSUE TITLE
유저 엔티티의 희망포지션 타입

### ISSUE THREAD

**Issue by pooreumu** [sayamae-amateur-baseball-platform/sayamae_be#2]
## 개요(문제 요약)
- 유저 엔티티의 필드 중 희망포지션 타입에는 어떤게 있나요?

## 문제 상황 설명
- 희망 포지션 타입을 union type으로 만드려고 하는데 단순하게 타자, 투수는 아닐 것 같은데 이에 대해 세부적인 얘기를 나누지 않아서 union type 작성에 어려움이 있습니다.

## 요청 사항
- 생각하시는 유저의 희망 포지션을 알려주세요

**Comment by hyeonjun4460** [comment]
희망 포지션은 야구에 있는  포지션들을 전반적으로 넣으면 될 거 같아요! 다음과 같습니다.
- P:투수
- C: 포수
- 1B: 1루수
- 2B: 2루수
- 3B: 3루수
- SS: 유격수
- CF: 중견수
- RF: 우익수
- LF: 좌익수
- DH: 지명타자
