### ISSUE TITLE
CRLF/LF 이슈

### ISSUE THREAD

**Issue by hyeonjun4460** [sayamae-amateur-baseball-platform/sayamae_be#5]
## 개요(문제 요약)
- git pull을 받았을 때, user 폴더 쪽에서 CRLF 이슈가 떠서 이의 원인에 대한 확인이 필요합니다.
- 일단은 CRLF 이슈 해결한 코드 블럭만 따로 브랜치를 생성해서 dev에 PR 올려두겠습니다.

## 문제 상황 설명
```
delete 'CR'
```
- 위와 같은 lint 에러가 dev branch를 pull 받았을 때 떴습니다.
- 제 ide에서 files.eol 옵션은 LF인걸 확인했습니다.
- 관련해서 더 찾아보니, CRLF/LF는 다음과 같은 배경이 있다고 합니다.

1. Window는 기본적으로 CRLF로 라인을 끝내고, Mac, Linux는 LF로 끝낸다고 합니다.
2. git config에서 core.eol 옵션을 통해 이를 조정할 수 있는데, 기본값은 native로 OS의 기본 세팅을 따르고, crlf/lf 옵션으로 변경할 수 있다고 합니다.
3. git에서 commit하는 상황에서는 core.autocrlf 옵션을 통해 crlf/lf 이슈를 해결한다고 합니다.
1) 이 때, 기본설정은 false입니다. commit하거나 pull 하는 상황에서 원격저장소의 line ending 세팅을 그대로 따르는 것입니다.
2) true 설정은 window OS에서 주로 설정하는데, commit 시 LF로 변경, pull 시 CRLF로 변경하는 옵션이라 합니다.
3) input 설정은 Mac OS에서 주로 설정하는데, commit, pull 모두 LF를 그대로 사용하는 옵션이라 합니다.

## 요청 사항
- git config에서 core.eol이 어떻게 되어 있는지 확인부탁드립니다!
- IDE 설정에서 file.eol, endOfLine이 어떻게 되어 있는지 확인부탁드립니다!

**Comment by pooreumu** [comment]
git config: core.autocrlf=input
ide file.eol = lf
입니다!

**Comment by hyeonjun4460** [comment]
문제 해결되었습니다.

결론부터 말씀드리자면, window, mac 모두 각자 운영체제가 사용하는 개행문자를 사용하도록 하고,
prettierrc에 **endOfLine: auto** 옵션을 추가하는 것이 가장 바람직한 해결방법인 것 같습니다.

주말 간에 CRLF/LF 푸름님과 함께 테스트해본 내용 요약해보자면,

### 1. 문제 상황
- 현준(window) 컴퓨터에서 pull을 받았을 떄, **Delete 'cr'** 에러가 떴다.
- .prettierrc에는 endOfLine 옵션은 설정되어 있지 않았다. --> 기본 값(lf)을 따른다.
- 현준 컴퓨터의 개행문자 관련 설정은 다음과 같았다.
1) endOfLine: lf
2) files.eol: /n

### 2. 테스트를 통해 밝혀진 문제 원인
- window에서 git 로컬 저장소 core.autocrlf 옵션의 기본값은 true인 것으로 추론된다.
> 아무런 설정을 하지 않은 저장소에서 commit, pull 작업을 할 때, 파일이 LF에서 CRLF로 변경되는 것을 목격했다.
> 즉, window의 git 저장소에 대한 기본 설정 값에 따라, pull을 받아올 때 CRLF로 변경된 것입니다.
- 한편, .prettierrc의 endOfLine 기본 설정은 lf다.
- 그래서 pull을 받아오면 파일은 CRLF이므로 .prettierrc에 의해서 lint 에러가 발생한 것이다.

### 3. 도입 가능한 해결방안
#### 1) window 측에서 해결하기
- core.autocrlf = false
- IDE설정에서 files.eol, endOfLine을 lf로 두기.

#### 2) prettierrc 수정하기
- endOfLine= auto 추가하기

### 4. 결론
- 결론적으로, 2) 방안을 채택했습니다. 이유는 다음과 같습니다.
>  window 측에서는 git config, ide 옵션을 모두 바꾸어야 하기에, 팀원이 늘어나는 상황, 혹은 작업하는 컴퓨터를 바꾼다고 가정했을 때, 매번 이를 수정해야하는 번거로움이 있습니다.
> 반면, prettierrc만 바꾸는 것은 기존 운영체제의 설정은 유지한 채, 단순히 pull만 받으면 적용가능하기 때문입니다.
