### ISSUE TITLE
enum 값으로 숫자 -> 문자

### ISSUE THREAD

**Issue by pooreumu** [sayamae-amateur-baseball-platform/sayamae_be#8]
## 개요(문제 요약)
- 현재 enum으로 만든 타입의 값들이 전부 숫자인데 문자를 사용해야 될 것 같아요

## 문제 상황 설명
- 보통 enum의 값은 문자를 사용하는 거 같아요
![IMG_6684](https://github.com/sayamae-amateur-baseball-platform/sayamae_be/assets/99081225/0a11c4ee-3bc2-484e-b968-771499c7a16e)
[출처](https://jojoldu.tistory.com/720)

## 요청 사항
- 데이터 베이스에 저장할때 타입에 해당하는 값들을 int로 저장하려고(문자열보다 빠른 조회 성능) enum의 값을 number로 했는데 enum에 있는 original값을 사용하는 식으로 바꾸는게 좋을 것 같은데 어떻게 생각하시나요?

**Comment by pooreumu** [comment]
![스크린샷 2023-06-11 오전 12 11 53](https://github.com/sayamae-amateur-baseball-platform/sayamae_be/assets/99081225/559c190a-8c08-4942-89f1-3afc0d15c08c)

[1](https://stackoverflow.com/questions/40133249/mysql-performance-string-vs-integer)

라고 하네요

**Comment by hyeonjun4460** [comment]
네, db에서 큰 성능차이가 없다는 내용은 새삼 처음 알았네요! 감사합니다.
저도 enum 사용할 때, value 값 문자로 활용하도록 하겠습니다.
