### ISSUE TITLE
tsconfig strict 세부사항

### ISSUE THREAD

**Issue by pooreumu** [sayamae-amateur-baseball-platform/sayamae_be#9]
## 개요(문제 요약)
- 현재 추가한 strict: true 옵션이 일부만 적용되는 문제를 발견했습니다.

## 문제 상황 설명
-  strict: true 면 noImplicitAny, strictNullChecks, strictFunctionTypes, strictBindCallApply, strictPropertyInitialization, noImplicitThis, alwaysStrict 이 설정들이 전부 true가 되는데 저희가 strict: true로 설정한 의도도 전부 true로 하기 위해서 였고요. 근데 현재 저희 프로젝트 tsconfig설정을 보면 "strictNullChecks": false,"noImplicitAny": false, "strictBindCallApply": false 이렇게 세 설정이 false로 돼 있는데 이렇게 되면 저 설정들은 false로 적용이됩니다.

## 요청 사항
- 세 설정 전부 true가 되도록 적용하겠습니다.

**Comment by hyeonjun4460** [comment]
감사합니다! 내용 확인했고, PR 승인했습니다.

**Comment by hyeonjun4460** [comment]
strict : true 옵션만 있을 시, class에서 property를 사용하는 데 애로사항이 있습니다.
strict 옵션으로 사용할 시, property는 반드시 constructor에서 초기화 대상이 되어야 하는 것 같습니다.
하지만, 저희 같은 경우에는 현재 시점에서는 생성자 방식이 아니라, 정적 메소드 방식을 주로 활용할 것이기에, 일단 이 옵션을 추가하고 작업을 하는 것이 좋겠습니다.
